# Generated by Django 5.0.3 on 2024-03-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonLibs',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('imageLink', models.TextField()),
                ('onHold', models.BooleanField(default=True)),
            ],
        ),
    ]
