# Generated by Django 5.0.3 on 2024-03-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
