# Generated by Django 5.0.3 on 2024-05-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('visitTime', models.DateTimeField()),
                ('city', models.CharField(max_length=145)),
                ('country', models.CharField(max_length=135)),
                ('state', models.CharField(max_length=134)),
            ],
        ),
        migrations.DeleteModel(
            name='PythonLibs',
        ),
    ]
