# Generated by Django 5.0.3 on 2024-03-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T01', '0002_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNC',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('des', models.TextField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
