# Generated by Django 5.0.3 on 2024-05-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T01', '0003_cnc'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
