# Generated by Django 5.0.3 on 2024-05-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T01', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('visitTime', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CNC',
        ),
        migrations.DeleteModel(
            name='PythonLibs',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
