# Generated by Django 5.0.3 on 2024-05-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T01', '0005_visitor_delete_cnc_delete_pythonlibs_delete_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitTime',
            field=models.DateTimeField(),
        ),
    ]
