# Generated by Django 4.2.17 on 2025-01-18 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.URLField(default=None)),
                ('ip', models.GenericIPAddressField(default=None)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('accuracy', models.FloatField(help_text='Location accuracy in meters.')),
                ('latitude', models.FloatField(help_text='Latitude of the location.')),
                ('longitude', models.FloatField(help_text='Longitude of the location.')),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('altitude_accuracy', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Geolocation',
                'verbose_name_plural': 'Geolocations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
