# Generated by Django 4.2.17 on 2025-01-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T04', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocations',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='geolocations',
            name='altitude_accuracy',
        ),
        migrations.RemoveField(
            model_name='geolocations',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='geolocations',
            name='speed',
        ),
    ]
